# Generated by Django 3.0.4 on 2020-03-27 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Celular',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('marca', models.CharField(max_length=20)),
                ('refernecia', models.CharField(max_length=20)),
                ('serial', models.CharField(max_length=20)),
                ('imei', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('numero', models.IntegerField()),
            ],
        ),
    ]
