# Generated by Django 3.0.4 on 2020-03-27 21:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0001_initial'),
        ('celulares', '0002_celular_compra'),
    ]

    operations = [
        migrations.AddField(
            model_name='celular',
            name='empresa',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='empresas.Empresa'),
            preserve_default=False,
        ),
    ]
