# Generated by Django 3.0.4 on 2020-03-27 21:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_document'),
        ('celulares', '0003_celular_empresa'),
    ]

    operations = [
        migrations.AddField(
            model_name='celular',
            name='users',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='users.User'),
            preserve_default=False,
        ),
    ]
