# Generated by Django 3.0.6 on 2020-05-20 06:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_correo'),
        ('compras', '0004_auto_20200520_0015'),
        ('celulares', '0004_celular_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='celular',
            name='compra',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='compras.Compra'),
        ),
        migrations.AlterField(
            model_name='celular',
            name='users',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='users.User'),
        ),
    ]
