# Generated by Django 3.0.6 on 2020-05-20 06:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0004_auto_20200520_0015'),
        ('celulares', '0005_auto_20200520_0104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='celular',
            name='compra',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='compras.Compra'),
        ),
    ]
