# Generated by Django 3.0.4 on 2020-03-27 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Caracteristicas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('procesador', models.CharField(max_length=20)),
                ('generacion', models.IntegerField()),
                ('ram', models.IntegerField()),
                ('discoDuro', models.IntegerField()),
                ('estadoDD', models.CharField(max_length=20)),
            ],
        ),
    ]
