# Generated by Django 3.0.4 on 2020-03-27 20:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0002_compra_ordencompra'),
        ('activos', '0002_caracteristicas'),
    ]

    operations = [
        migrations.AddField(
            model_name='activo',
            name='compra',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='compras.Compra'),
        ),
    ]
