# Generated by Django 3.0.4 on 2020-03-27 20:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0001_initial'),
        ('activos', '0003_activo_compra'),
    ]

    operations = [
        migrations.AddField(
            model_name='activo',
            name='empresa',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='empresas.Empresa'),
            preserve_default=False,
        ),
    ]
