# Generated by Django 3.0.4 on 2020-03-27 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0004_activo_empresa'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Caracteristicas',
            new_name='Caracteristica',
        ),
    ]
