# Generated by Django 3.0.4 on 2020-03-27 21:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_document'),
        ('activos', '0005_auto_20200327_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='activo',
            name='user',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='users.User'),
            preserve_default=False,
        ),
    ]
