# Generated by Django 3.0.4 on 2020-03-27 21:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('partes', '0002_parte_compra'),
        ('activos', '0006_activo_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='activo',
            name='parte',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='partes.Parte'),
        ),
    ]
