# Generated by Django 3.0.4 on 2020-03-28 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0007_activo_parte'),
    ]

    operations = [
        migrations.AddField(
            model_name='activo',
            name='caracteristicas',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='activos.Caracteristica'),
        ),
    ]
