# Generated by Django 3.0.4 on 2020-03-27 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='ordenCompra',
            field=models.IntegerField(null=True),
        ),
    ]
