# Generated by Django 3.0.6 on 2020-05-20 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0002_compra_ordencompra'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='fecha',
            field=models.DateField(null=True),
            preserve_default=False,
        ),
    ]
