# Generated by Django 3.0.4 on 2020-03-27 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomCiudad', models.CharField(max_length=20)),
                ('nomSucursal', models.CharField(max_length=20)),
            ],
        ),
    ]
