# Generated by Django 3.0.6 on 2020-05-20 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empresa',
            old_name='nomSucursal',
            new_name='nomEmpresa',
        ),
        migrations.AddField(
            model_name='empresa',
            name='nomSubdivision',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
