# Generated by Django 3.0.6 on 2020-05-20 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0002_auto_20200519_2309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='nomSubdivision',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
